"""inicial

Revision ID: 5088faeafb22
Revises: 
Create Date: 2023-10-22 19:44:58.307525

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5088faeafb22'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias_ST',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=25), nullable=True),
    sa.Column('Descripcion', sa.String(length=255), nullable=True),
    sa.Column('Aplicacion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('localidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Codigo', sa.String(length=25), nullable=True),
    sa.Column('Descripcion', sa.String(length=255), nullable=True),
    sa.Column('Ubicacion', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('password', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=20), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('Rol', sa.Enum('base', 'admin', name='roletype'), server_default='base', nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('situaciones_anormales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Nombre', sa.String(length=25), nullable=True),
    sa.Column('TipoActorVial', sa.String(length=255), nullable=True),
    sa.Column('Localidad_id', sa.Integer(), nullable=False),
    sa.Column('latitud', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('longitud', sa.Numeric(precision=10, scale=6), nullable=True),
    sa.Column('ExistenciaSenalesTransito', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['Localidad_id'], ['localidades.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('estadisticas_SV',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('Resporte_id', sa.Integer(), nullable=True),
    sa.Column('Contenido', sa.String(length=255), nullable=True),
    sa.Column('TipoEstadistica', sa.String(length=50), nullable=True),
    sa.Column('Responsable_id', sa.Integer(), nullable=True),
    sa.Column('Anio', sa.Integer(), nullable=True),
    sa.Column('Mes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['Responsable_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['Resporte_id'], ['situaciones_anormales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('estadisticas_SV')
    op.drop_table('situaciones_anormales')
    op.drop_table('usuarios')
    op.drop_table('localidades')
    op.drop_table('categorias_ST')
    # ### end Alembic commands ###
